### ISSUE TITLE
config rethinkdb

### ISSUE THREAD

**Issue by devgripes** [ViZhe/react-producter#64]
Hi, can you share your config.rethinkdb file? 
I'm really looking into learning Horizon and I saw this project.
Thanks

**Comment by ViZhe** [comment]
Hey, sorry for the long answer, I somehow missed this issue ;(

I am also only beginning to understand rethinkdb. But for myself, decided to abandon the horizon in favor of [thinky](http://thinky.io/), as it gives you more control.

Started to describe [API](https://github.com/ViZhe/react-producter/tree/master/server/api), but time is not enough.

```
// config.rethinkdb.js

export const configDb = {
  project_name: 'PROJECT_NAME',
  permissions: false,
  auto_create_collection: true,
  auto_create_index: true,
  auth:{
    allow_anonymous: true,
    allow_unauthenticated: true,
    token_secret: 'TOKEN_SECRET'
  }
}

```
